//User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const EDIT_USER_NAME = "EDIT_USER_NAME";
export const SET_USER = "SET_USER";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
//Data reducer types
export const SET_TAB_NAVIGATION = "SET_TAB_NAVIGATION";
export const SET_SELECTED_GROUP = "SET_SELECTED_GROUP";
export const SET_CLASSES_IN_CHAT_TAB = "SET_CLASSES_IN_CHAT_TAB";
export const SET_NEW_MESSAGE = "SET_NEW_MESSAGE";
export const SET_CHOSEN_CLASS = "SET_CHOSEN_CLASS";
export const SET_TYPING = "SET_TYPING";
export const SET_DELETED_USER = "SET_DELETED_USER";
export const SET_ROOM_DETAIL_CHAT_TAB = "SET_ROOM_DETAIL_CHAT_TAB";
export const SET_DELETED_ROOM = "SET_DELETED_ROOM";
export const UPDATE_ROOM_AVATAR = "UPDATE_ROOM_AVATAR";
export const SET_SEEN_ROOMS = "SET_SEEN_ROOMS";
export const SET_SEEN_MESSAGE = "SET_SEEN_MESSAGE";
export const SET_FILES_PROFILE_TAB = "SET_FILES_PROFILE_TAB";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const SET_STAFF_DATA = "SET_STAFF_DATA";
export const SET_NEW_USER_STAFF = "SET_NEW_USER_STAFF";
export const SET_USER_ONLINE = "SET_USER_ONLINE";
export const SET_NEW_ROOM = "SET_NEW_ROOM";
export const SET_CALL_VIDEO = "SET_CALL_VIDEO";
export const SET_MORE_MESSAGE = "SET_MORE_MESSAGE";
export const SET_CLASS_SHOW_COLLAPSE = "SET_CLASS_SHOW_COLLAPSE";
export const SET_MORE_ROOMS = "SET_MORE_ROOMS";
export const SET_REPLY_TO_MESSAGE = "SET_REPLY_TO_MESSAGE";
export const UPDATE_LIST_ROOM = "UPDATE_LIST_ROOM";
export const SET_CLOSE_CHAT_MOBILE = "SET_CLOSE_CHAT_MOBILE";
//Loading
export const SET_LOADING = "SET_LOADING";
